boot.o: boot.S multiboot.h x86_desc.h types.h
sys_calls_handler.o: sys_calls_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_sys.o: file_sys.c file_sys.h lib.h types.h sys_calls.h paging.h \
  x86_desc.h keyboard.h i8259.h RTC.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupts.o: interrupts.c x86_desc.h types.h interrupts.h lib.h i8259.h \
  RTC.h keyboard.h sys_calls.h file_sys.h paging.h pit.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h RTC.h \
  debug.h tests.h interrupts.h keyboard.h paging.h file_sys.h sys_calls.h \
  pit.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h sys_calls.h \
  file_sys.h paging.h x86_desc.h RTC.h pit.h
lib.o: lib.c lib.h types.h sys_calls.h file_sys.h paging.h x86_desc.h \
  keyboard.h i8259.h RTC.h pit.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h
pit.o: pit.c pit.h types.h lib.h i8259.h sys_calls.h file_sys.h paging.h \
  x86_desc.h keyboard.h RTC.h
RTC.o: RTC.c RTC.h types.h lib.h i8259.h pit.h sys_calls.h file_sys.h \
  paging.h x86_desc.h keyboard.h
sys_calls.o: sys_calls.c sys_calls.h types.h file_sys.h lib.h paging.h \
  x86_desc.h keyboard.h i8259.h RTC.h pit.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h RTC.h \
  keyboard.h file_sys.h sys_calls.h paging.h
